#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#
<<<<<<<< HEAD:drivers/misc/mediatek/imgsensor/src/mt6768/camera_project/selene/camera_hw/Makefile
ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/inc \

obj-y		+= regulator/
obj-y		+= gpio/
#obj-y		+= mt6306/
obj-y		+= mclk/
obj-y		+= imgsensor_cfg_table.o
========

obj-y += nt36672c_fhdp_dsi_vdo_90hz_shenchao_6382.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
>>>>>>>> 4ccec69:drivers/misc/mediatek/lcm/nt36672c_fhdp_dsi_vdo_90hz_shenchao_6382/Makefile
