#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

<<<<<<<< HEAD:drivers/misc/mediatek/imgsensor/src/mt6768/camera_project/selene/s5kjn1_ofilm_main_mipi_raw/Makefile
obj-y += s5kjn1_ofilm_main_mipi_raw.o
========
obj-y += ov50c40_ofilm_main_mipi_raw.o
>>>>>>>> 4ccec69:drivers/misc/mediatek/imgsensor/src/mt6768/camera_project/selene/ov50c40_ofilm_main_mipi_raw/Makefile

